version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: news_aggregator_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-news_aggregator}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - news_network

  # Laravel Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_aggregator_backend
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - .:/var/www/html
      - backend_storage:/var/www/html/storage
    env_file:
      - .env
    environment:
      # Override specific Docker-related settings
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - news_network

  # Redis (for caching and queues)
  redis:
    image: redis:7-alpine
    container_name: news_aggregator_redis
    restart: unless-stopped
    ports:
      - "${REDIS_EXTERNAL_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    networks:
      - news_network

volumes:
  postgres_data:
  backend_storage:
  redis_data:

networks:
  news_network:
    driver: bridge
